services:

  app:
    container_name: ci_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - ci_network
    depends_on:
      - db

  web:
    container_name: ci_web
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ci_network
    depends_on:
      - app

  db:
    container_name: ci_db
    image: mysql:5.7
    restart: unless-stopped
    environment:
    - DB_HOST=${DB_HOST}
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_DATABASE=${DB_DATABASE}
    - CONFIG_BASE_URL=${CONFIG_BASE_URL}
    - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "3307:3306"        # host 3307 so it won't clash with a local MySQL
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ci_network

networks:
  ci_network:
    driver: bridge

volumes:
  db_data: