name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          cd /home/ubuntu/hyperion
          git pull origin main
          cp .env_production .env
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up -d --build
          docker system prune -f