name: Deploy to EC2

on:
  push:
    branches:
      - main  # change to your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/hyperion
            git pull origin main
            cp .env_production .env
            docker compose down
            docker compose up -d --build
            docker system prune -f